"""add planner_agent_id to orchestrator_tasks

Revision ID: 630cc95100f2
Revises: 7e319cd8e98b
Create Date: 2026-06-01 23:26:34.531436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '630cc95100f2'
down_revision: Union[str, None] = '7e319cd8e98b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orchestrator_tasks', sa.Column('planner_agent_id', sa.UUID(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orchestrator_tasks', 'planner_agent_id')
    # ### end Alembic commands ###
