"""add api_key and base_url to agents

Revision ID: 7e319cd8e98b
Revises: 0005
Create Date: 2026-06-01 20:02:32.179166

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e319cd8e98b'
down_revision: Union[str, None] = '0005'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('api_key', sa.String(length=500), nullable=True))
    op.add_column('agents', sa.Column('base_url', sa.String(length=500), nullable=True))
    op.drop_index(op.f('idx_vc_email_purpose'), table_name='verification_codes')
    op.create_index(op.f('ix_verification_codes_email'), 'verification_codes', ['email'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_verification_codes_email'), table_name='verification_codes')
    op.create_index(op.f('idx_vc_email_purpose'), 'verification_codes', ['email', 'purpose'], unique=False)
    op.drop_column('agents', 'base_url')
    op.drop_column('agents', 'api_key')
    # ### end Alembic commands ###
